### ISSUE TITLE
"HomeViewModel" not found.

### ISSUE THREAD

**Issue by bill-bil** [AhmedLSayed9/shopzler#2]
![image](https://user-images.githubusercontent.com/74221254/136313794-92a144d5-d2d7-45a0-9bbc-cd71e1fe23d1.png)

**Comment by AhmedLSayed9** [comment]
Are you sure you've "Get.lazyPut(() => HomeViewModel());" in helper/binding.dart file?

**Comment by bill-bil** [comment]
> Are you sure you've "Get.lazyPut(() => HomeViewModel());" in helper/binding.dart file?

yes, i sure .
![image](https://user-images.githubusercontent.com/74221254/136399854-6c05578d-5f1f-45c2-aefa-4f8712df354d.png)

**Comment by AhmedLSayed9** [comment]
![Capture](https://user-images.githubusercontent.com/70890146/136407035-d1db7d4f-e693-4e12-8ac8-fe9d5e43dd86.PNG)
I've cloned the code to new project to test it again and It's working fine here. Please re-install the app and try again. Also, Let me know what changes have you made to the code?
