### ISSUE TITLE
Firebase Product Models Data 

### ISSUE THREAD

**Issue by Ghazanfarrajpoot** [AhmedLSayed9/shopzler#4]
Great work mate.
everything works perfectly until i use my own firebase account.
ive successfully added categories but im unable to add products. can you share your firebase firestore screenshot of products collection.
thankyou.

**Comment by AhmedLSayed9** [comment]
**There you go:**

![Capture](https://user-images.githubusercontent.com/70890146/145680439-b467b9c8-8546-48e6-a974-059c9af227cb.PNG)
